apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: aquarela-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  source:
    repoURL: https://github.com/CHANGE-ME/aquarela.git
    targetRevision: HEAD
    path: gitops/platform/elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
