apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: aquarela-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop
  source:
    repoURL: https://github.com/CHANGE-ME/aquarela.git
    targetRevision: HEAD
    path: gitops/apps/sock-shop/frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
