apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aquarela-apps
  namespace: argocd
spec:
  description: Application workloads managed by Argo CD.
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
